name:                creatur
version:             5.9.24
github:              "mhwombat/creatur"
license:             BSD3
author:              "Amy de Buitléir"
maintainer:          "amy@nualeargais.ie"
copyright:           "2018 Amy de Buitléir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mhwombat/creatur#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - binary
  - bytestring
  - cereal
  - cond
  - directory
  - exceptions
  - filepath
  - gray-extended
  - hdaemonize
  - hsyslog
  - MonadRandom
  - mtl
  - random
  - split
  - time
  - transformers
  - unix

tests:
  creatur-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - creatur
    - cereal
    - directory
    - filepath
    - HUnit
    - MonadRandom
    - mtl
    - QuickCheck
    - temporary
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2

